config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do

    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'

  end
  
  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  
  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
    #redirect_to request.referer
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
   # redirect_to request.referer
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment], local: false do |f|%>
           <%= f.text_area :comment, size:"90x5" %>
           <br><%= f.submit "送信" %>
           <% end %>

app/views/book_comments/_index.html.erb
 <% book.book_comments.each do |book_comment| %>
            <tr>
               <td><%= link_to user_path(book_comment.user) do %>
               <%= image_tag book.user.get_profile_image, size:"100x100" %><br>
               <%= book_comment.user.name %>
              <% end %>
              </td>
              <td><%= book_comment.comment %></td>
              <% if book_comment.user == current_user %>
               <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger", local: false, remote: true %></td>
              <% end %>
            </tr>
<% end %>

app/views/book_comments/create.js.erb
$(".book_<%= @book.id %>_comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/book_comments/destroy.js.erb
$(".book_<%= @book.id %>_comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");