config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do

    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'

  end
  
  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  # フォローをした、されたの関係
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

# 一覧画面で使う
has_many :followings, through: :relationships, source: :followed
has_many :followers, through: :reverse_of_relationships, source: :follower

has_one_attached :profile_image
  
validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
validates :introduction, length: { maximum: 50 }
  
 
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end


# フォローしたときの処理
def follow(user_id)
  relationships.create(followed_id: user_id)
end
# フォローを外すときの処理
def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end
# フォローしているか判定
def following?(user)
  followings.include?(user)
end


# 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
    
  end
  
  def followings
    user = User.find(params[:id])
    @users = user.followings
  end
  
  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
    

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user) 
    end
  end


  def update
     @user = User.find(params[:id])
     if @user.update(user_params)
      flash[:notice] =  "You habe updated user successfully."
      redirect_to user_path(@user)
     else
      render :edit
     end
  end
 
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_book_index.html.erb
<h3>投稿数の前日比・前週比</h3>
  <div class="table_width">
    <table class='table table-bordered'>
     <thead>
      <tr>
       <th>今日の投稿数</th>
       <th>前日の投稿数</th>
       <th>前日比</th>
      </tr>
     </thead>
     <tbody>
      <tr>
      　<td><%= @today_book.count %></td>
      　<td><%= @yesterday_book.count %></td>
      　<td>
        <% if @yesterday_book.count == 0 %>
         前日の投稿はありません
        <% else %>
        　<% @the_day_before =   @today_book.count / @yesterday_book.count.to_f  %>
        　<%= (@the_day_before * 100).round %>
        <% end %>
       </td>
      </tr>
     </tbody>
   </table>
  </div>
<div class="table_width">
    <table class='table table-bordered'>
      <thead>
        <tr>
         <th>今週の投稿数</th>
         <th>先週の投稿数</th>
         <th>前週比</th>
        </tr>
      </thead>
      <tbody>
        <tr>
         <td><%= @this_week_book.count %></td>
         <td><%= @last_week_book.count %></td>
          <td><% if @last_week_book.count == 0 %>
                 先週の投稿はなし</td>
              <% else %>
       <% @the_week_before =   @this_week_book.count / @last_week_book.count.to_f  %>
       <%= (@the_week_before * 100).round %>%
     <% end %>
     </td>
     </tr>
   </tbody>
  </table>
</div>
<h4>7日間分の投稿数</h4>
  <table class='table table-bordered'>
   <thead>
    <tr>
     <th>6日前</th>
     <th>5日前</th>
     <th>4日前</th>
     <th>3日前</th>
     <th>2日前</th>
     <th>1日前</th>
     <th>今日</th>
    </tr>
   </thead>
   <tbody>
    <tr>
     　　<td><%= @books.created_6day_ago.count %></td>
        <td><%= @books.created_5day_ago.count %></td>
        <td><%= @books.created_4day_ago.count %></td>
        <td><%= @books.created_3day_ago.count %></td>
        <td><%= @books.created_2day_ago.count %></td>
        <td><%= @books.created_yesterday.count %></td>
        <td><%= @books.created_today.count %></td>
    </tr>
   </tbody>
  </table>
  <canvas id="myChart" width="300" height="100"> </canvas>

    <script> 
    var ctx = document.getElementById("myChart").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'line',                      
        data: {
            labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
            datasets: [
              {
                label: "投稿数",
                data: [
                  <%= @books.created_6day_ago.count %>,
                  <%= @books.created_5day_ago.count %>,
                  <%= @books.created_4day_ago.count %>,
                  <%= @books.created_3day_ago.count %>,
                  <%= @books.created_2day_ago.count %>,
                  <%= @yesterday_book.count %>,
                  <%= @today_book.count%>],
                backgroundColor: 'rgba(255, 80, 120, 1.0)',
                borderColor: 'rgba(255, 80, 120, 1.0)',
                fill: false
            }]
        },
    });
</script>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= user.followings.count %>フォロー</td>
        <td><%= user.followers.count %>フォロワー</td> 
        <td><% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
        <% end %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr> 
　 <th>follows</th>
　 <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
　</tr>
  <tr>
　 <th>followers</th>
　 <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
</tr>
</table>



     <% if current_user.following?(user) %>
  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
<% end %>
  




　
<div class='row'>
  <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
          <%= render 'info', user: current_user %>
          <h2 class="mt-3">New book</h2>
          <%= render 'books/form', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">  
        <h2>Users</h2>
        <%= render 'index',users: @users, user: @user, others: @others %>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <%= render 'book_index',books: @books %>

  </div>
  </div>
</div>